### PR TITLE
Kdlt branch

### PR DESCRIPTION
**Pull request by Kdlt2017**
I did brought updates to EntrepriseProfile entities, User Entities and Implemented some required services for JobOffer management

### CODE REVIEW

**Comment by amine177** [comment]
This pull request **introduces 8 alerts** when merging 4bdb866b924dc890c5df6b9e16c512290efaf35f into 3cabdcdfe2ba99bf1c528318e3d9a4d7f0e31db3 - [view on LGTM.com](https://lgtm.com/projects/g/amine177/piJEE/rev/pr-afa54862583351d88d015c74d10361d02ad8be15)

**new alerts:**

* 8 for Contradictory type checks

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by amine177** [comment]
This pull request **introduces 8 alerts** when merging 1cb5ff1cba4f34a50845ea519787f99e8639a885 into 3cabdcdfe2ba99bf1c528318e3d9a4d7f0e31db3 - [view on LGTM.com](https://lgtm.com/projects/g/amine177/piJEE/rev/pr-bca9f3c179c137614be24565c9deaaaa1207f6ed)

**new alerts:**

* 8 for Contradictory type checks

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Kdlt2017** [comment]
Can u be explicit on y u reject my pull request please. I dont get it quite well

**Comment by amine177** [comment]
> Can u be explicit on y u reject my pull request please. I dont get it quite well


It was an automated alert from the code quality tool.
As it said, testing that something is instanceof is bad. You have a discriminator column use it instead and cast.

**Pull request merged**
